version: 2
updates:
  # Backend Dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    
  # Frontend Dependencies
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  # Docker Action Updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
